'''
@File : output_formater.py

@Brief: This script is used to update the scores in the original CSV file.
        The originall csv file that is the source of SQL answers contains other answers which are not graded using SOCOLES.
        We therefore grade only SQL questions and output the scores in a file named quiz_graded.csv.
        This script is used to update the scores in the original CSV file with the scores in quiz_graded.csv generated by SOCOLES.
        
@Author: Benard Wanjiru
@Email: benard.wanjiru@ru.nl
'''
import pandas as pd
import sys

if len(sys.argv) != 3:
    print("Usage: python output_formater.py <original_csv> <graded_csv>")
    print("Example: python output_formater.py original_csv.csv graded_csv.csv")
    sys.exit(1)
    
# Get the paths to the CSV files
original_csv_path = sys.argv[1]
socoles_csv_path = sys.argv[2]

# Load the two CSV files
original_df = pd.read_csv(original_csv_path)
socoles_df = pd.read_csv(socoles_csv_path)

# Initialize the 'Feedback' column in original_df if it doesn't exist
if 'Feedback' not in original_df.columns:
    original_df['Feedback'] = None

# Merge the DataFrames
#The column names must be named exactly as the csv files
merge_columns = ['Org Defined ID', 'Attempt #', 'Q #']
merged_df = pd.merge(original_df, socoles_df, how='left', on=merge_columns, suffixes=('', '_graded'))

# Update the original Dataframe with the merged data
update_columns = ['Score', 'Out Of', 'Feedback']
for col in update_columns:
    if col in socoles_df.columns:
         # Update only if the '_graded' column is not null (indicating a match was found)
        mask = ~merged_df[col + '_graded'].isnull()
        original_df.loc[mask, col] = merged_df.loc[mask, col + '_graded']

#save the dataframe to a csv file
updated_csv_path = 'updated_original.csv'  
original_df.to_csv(updated_csv_path, index=False)

print("Updated CSV file saved.")
